import { CurrencyOption } from "./types";

export const CURRENCY_OPTIONS: CurrencyOption[] = [
  { value: "AED", countryCode: "ae", countryName: "United Arab Emirates" },
  { value: "AFN", countryCode: "af", countryName: "Afghanistan" },
  { value: "ALL", countryCode: "al", countryName: "Albania" },
  { value: "AMD", countryCode: "am", countryName: "Armenia" },
  { value: "ANG", countryCode: "an", countryName: "Netherlands Antilles" },
  { value: "AOA", countryCode: "ao", countryName: "Angola" },
  { value: "ARS", countryCode: "ar", countryName: "Argentina" },
  { value: "AUD", countryCode: "au", countryName: "Australia" },
  { value: "AZN", countryCode: "az", countryName: "Azerbaijan" },

  { value: "BAM", countryCode: "ba", countryName: "Bosnia and Herzegovina" },
  { value: "BBD", countryCode: "bb", countryName: "Barbados" },
  { value: "BDT", countryCode: "bd", countryName: "Bangladesh" },
  { value: "BGN", countryCode: "bg", countryName: "Bulgaria" },
  { value: "BHD", countryCode: "bh", countryName: "Bahrain" },
  { value: "BIF", countryCode: "bi", countryName: "Burundi" },
  { value: "BMD", countryCode: "bm", countryName: "Bermuda" },
  { value: "BND", countryCode: "bn", countryName: "Brunei" },
  { value: "BOB", countryCode: "bo", countryName: "Bolivia" },
  { value: "BRL", countryCode: "br", countryName: "Brazil" },
  { value: "BSD", countryCode: "bs", countryName: "Bahamas" },
  { value: "BTN", countryCode: "bt", countryName: "Bhutan" },
  { value: "BWP", countryCode: "bw", countryName: "Botswana" },
  { value: "BYN", countryCode: "by", countryName: "Belarus" },
  { value: "BZD", countryCode: "bz", countryName: "Belize" },

  { value: "CAD", countryCode: "ca", countryName: "Canada" },
  { value: "CDF", countryCode: "cd", countryName: "Congo (DRC)" },
  { value: "CHF", countryCode: "ch", countryName: "Switzerland" },
  { value: "CLP", countryCode: "cl", countryName: "Chile" },
  { value: "CNY", countryCode: "cn", countryName: "China" },
  { value: "COP", countryCode: "co", countryName: "Colombia" },
  { value: "CRC", countryCode: "cr", countryName: "Costa Rica" },
  { value: "CUP", countryCode: "cu", countryName: "Cuba" },
  { value: "CVE", countryCode: "cv", countryName: "Cape Verde" },
  { value: "CZK", countryCode: "cz", countryName: "Czech Republic" },

  { value: "DJF", countryCode: "dj", countryName: "Djibouti" },
  { value: "DKK", countryCode: "dk", countryName: "Denmark" },
  { value: "DOP", countryCode: "do", countryName: "Dominican Republic" },
  { value: "DZD", countryCode: "dz", countryName: "Algeria" },

  { value: "EGP", countryCode: "eg", countryName: "Egypt" },
  { value: "ERN", countryCode: "er", countryName: "Eritrea" },
  { value: "ETB", countryCode: "et", countryName: "Ethiopia" },

  { value: "FJD", countryCode: "fj", countryName: "Fiji" },
  { value: "FKP", countryCode: "fk", countryName: "Falkland Islands" },

  { value: "GEL", countryCode: "ge", countryName: "Georgia" },
  { value: "GGP", countryCode: "gg", countryName: "Guernsey" },
  { value: "GHS", countryCode: "gh", countryName: "Ghana" },
  { value: "GIP", countryCode: "gi", countryName: "Gibraltar" },
  { value: "GMD", countryCode: "gm", countryName: "Gambia" },
  { value: "GNF", countryCode: "gn", countryName: "Guinea" },
  { value: "GTQ", countryCode: "gt", countryName: "Guatemala" },
  { value: "GYD", countryCode: "gy", countryName: "Guyana" },

  { value: "HKD", countryCode: "hk", countryName: "Hong Kong" },
  { value: "HNL", countryCode: "hn", countryName: "Honduras" },
  { value: "HRK", countryCode: "hr", countryName: "Croatia" },
  { value: "HTG", countryCode: "ht", countryName: "Haiti" },
  { value: "HUF", countryCode: "hu", countryName: "Hungary" },

  { value: "IDR", countryCode: "id", countryName: "Indonesia" },
  { value: "ILS", countryCode: "il", countryName: "Israel" },
  { value: "IMP", countryCode: "im", countryName: "Isle of Man" },
  { value: "INR", countryCode: "in", countryName: "India" },
  { value: "IQD", countryCode: "iq", countryName: "Iraq" },
  { value: "IRR", countryCode: "ir", countryName: "Iran" },
  { value: "ISK", countryCode: "is", countryName: "Iceland" },

  { value: "JEP", countryCode: "je", countryName: "Jersey" },
  { value: "JMD", countryCode: "jm", countryName: "Jamaica" },
  { value: "JOD", countryCode: "jo", countryName: "Jordan" },
  { value: "JPY", countryCode: "jp", countryName: "Japan" },

  { value: "KES", countryCode: "ke", countryName: "Kenya" },
  { value: "KGS", countryCode: "kg", countryName: "Kyrgyzstan" },
  { value: "KHR", countryCode: "kh", countryName: "Cambodia" },
  { value: "KMF", countryCode: "km", countryName: "Comoros" },
  { value: "KPW", countryCode: "kp", countryName: "North Korea" },
  { value: "KRW", countryCode: "kr", countryName: "South Korea" },
  { value: "KWD", countryCode: "kw", countryName: "Kuwait" },
  { value: "KYD", countryCode: "ky", countryName: "Cayman Islands" },
  { value: "KZT", countryCode: "kz", countryName: "Kazakhstan" },

  { value: "LAK", countryCode: "la", countryName: "Laos" },
  { value: "LBP", countryCode: "lb", countryName: "Lebanon" },
  { value: "LKR", countryCode: "lk", countryName: "Sri Lanka" },
  { value: "LRD", countryCode: "lr", countryName: "Liberia" },
  { value: "LSL", countryCode: "ls", countryName: "Lesotho" },
  { value: "LYD", countryCode: "ly", countryName: "Libya" },

  { value: "MAD", countryCode: "ma", countryName: "Morocco" },
  { value: "MDL", countryCode: "md", countryName: "Moldova" },
  { value: "MGA", countryCode: "mg", countryName: "Madagascar" },
  { value: "MKD", countryCode: "mk", countryName: "North Macedonia" },
  { value: "MMK", countryCode: "mm", countryName: "Myanmar" },
  { value: "MNT", countryCode: "mn", countryName: "Mongolia" },
  { value: "MOP", countryCode: "mo", countryName: "Macau" },
  { value: "MRO", countryCode: "mr", countryName: "Mauritania" },
  { value: "MUR", countryCode: "mu", countryName: "Mauritius" },
  { value: "MVR", countryCode: "mv", countryName: "Maldives" },
  { value: "MWK", countryCode: "mw", countryName: "Malawi" },
  { value: "MXN", countryCode: "mx", countryName: "Mexico" },
  { value: "MYR", countryCode: "my", countryName: "Malaysia" },
  { value: "MZN", countryCode: "mz", countryName: "Mozambique" },

  { value: "NAD", countryCode: "na", countryName: "Namibia" },
  { value: "NGN", countryCode: "ng", countryName: "Nigeria" },
  { value: "NIO", countryCode: "ni", countryName: "Nicaragua" },
  { value: "NOK", countryCode: "no", countryName: "Norway" },
  { value: "NPR", countryCode: "np", countryName: "Nepal" },
  { value: "NZD", countryCode: "nz", countryName: "New Zealand" },

  { value: "OMR", countryCode: "om", countryName: "Oman" },

  { value: "PAB", countryCode: "pa", countryName: "Panama" },
  { value: "PEN", countryCode: "pe", countryName: "Peru" },
  { value: "PGK", countryCode: "pg", countryName: "Papua New Guinea" },
  { value: "PHP", countryCode: "ph", countryName: "Philippines" },
  { value: "PKR", countryCode: "pk", countryName: "Pakistan" },
  { value: "PLN", countryCode: "pl", countryName: "Poland" },
  { value: "PYG", countryCode: "py", countryName: "Paraguay" },

  { value: "QAR", countryCode: "qa", countryName: "Qatar" },

  { value: "RON", countryCode: "ro", countryName: "Romania" },
  { value: "RSD", countryCode: "rs", countryName: "Serbia" },
  { value: "RUB", countryCode: "ru", countryName: "Russia" },
  { value: "RWF", countryCode: "rw", countryName: "Rwanda" },

  { value: "SAR", countryCode: "sa", countryName: "Saudi Arabia" },
  { value: "SBD", countryCode: "sb", countryName: "Solomon Islands" },
  { value: "SCR", countryCode: "sc", countryName: "Seychelles" },
  { value: "SDG", countryCode: "sd", countryName: "Sudan" },
  { value: "SEK", countryCode: "se", countryName: "Sweden" },
  { value: "SGD", countryCode: "sg", countryName: "Singapore" },
  { value: "SHP", countryCode: "sh", countryName: "Saint Helena" },
  { value: "SLL", countryCode: "sl", countryName: "Sierra Leone" },
  { value: "SOS", countryCode: "so", countryName: "Somalia" },
  { value: "SRD", countryCode: "sr", countryName: "Suriname" },
  { value: "SSP", countryCode: "ss", countryName: "South Sudan" },
  { value: "STN", countryCode: "st", countryName: "São Tomé and Príncipe" },
  { value: "SYP", countryCode: "sy", countryName: "Syria" },
  { value: "SZL", countryCode: "sz", countryName: "Eswatini" },

  { value: "THB", countryCode: "th", countryName: "Thailand" },
  { value: "TJS", countryCode: "tj", countryName: "Tajikistan" },
  { value: "TMT", countryCode: "tm", countryName: "Turkmenistan" },
  { value: "TND", countryCode: "tn", countryName: "Tunisia" },
  { value: "TOP", countryCode: "to", countryName: "Tonga" },
  { value: "TRY", countryCode: "tr", countryName: "Turkey" },
  { value: "TTD", countryCode: "tt", countryName: "Trinidad and Tobago" },
  { value: "TWD", countryCode: "tw", countryName: "Taiwan" },
  { value: "TZS", countryCode: "tz", countryName: "Tanzania" },

  { value: "UAH", countryCode: "ua", countryName: "Ukraine" },
  { value: "UGX", countryCode: "ug", countryName: "Uganda" },
  { value: "USD", countryCode: "us", countryName: "United States" },
  { value: "UYU", countryCode: "uy", countryName: "Uruguay" },
  { value: "UZS", countryCode: "uz", countryName: "Uzbekistan" },

  { value: "VES", countryCode: "ve", countryName: "Venezuela" },
  { value: "VND", countryCode: "vn", countryName: "Vietnam" },
  { value: "VUV", countryCode: "vu", countryName: "Vanuatu" },

  { value: "WST", countryCode: "ws", countryName: "Samoa" },

  { value: "XAF", countryCode: "cm", countryName: "Cameroon (Central Africa)" },
  { value: "XCD", countryCode: "ag", countryName: "Eastern Caribbean" },
  { value: "XOF", countryCode: "sn", countryName: "West Africa" },
  { value: "XPF", countryCode: "pf", countryName: "French Polynesia" },

  { value: "YER", countryCode: "ye", countryName: "Yemen" },

  { value: "ZAR", countryCode: "za", countryName: "South Africa" },
  { value: "ZMW", countryCode: "zm", countryName: "Zambia" },
  { value: "ZWL", countryCode: "zw", countryName: "Zimbabwe" }
];
