import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/app/shared/components/common/navigation/Navbar";
import { ReduxProvider } from "@/src/app/shared/providers/ReduxProvider";
import AuthInitializer from "@/src/app/shared/providers/AuthInitializer";
import Footer from "@/src/app/shared/components/common/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-300">
        <ReduxProvider>
          <Navbar />
          <AuthInitializer>{children}</AuthInitializer>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
